### add restaurant
POST http://localhost:8080/restaurants
Content-Type: application/json

{
  "name": "keks",
  "dishes": "haha"
}

### get all restaurants
GET http://localhost:8080/restaurants/all

### get restaurant by id
GET http://localhost:8080/restaurants/6

###
DELETE http://localhost:8080/restaurants/1

###
PUT http://localhost:8080/restaurants/3
Content-Type: application/json

{
  "name": "keksksks",
  "dishes": "haha"
}
