### add notification
POST http://localhost:8091/api/notifications
Content-Type: application/json

{
  "agents": [2],
  "notification_name": "New Notification 4",
  "priority": 2,
  "notification_text": "This is a new notification",
  "admin_full_name": "John Doe",
  "is_broadcast_notification": false,
  "is_periodic_notification": true,
  "period_type": 1,
  "is_blocked": false
}

###update notification
PUT http://localhost:8091/api/notifications/37
Content-Type: application/json

{
  "agents": [2],
  "notification_name": "New Notification 2121654",
  "priority": 3,
  "notification_text": "This is a new notification",
  "admin_full_name": "John Doe",
  "is_broadcast_notification": false,
  "is_periodic_notification": true,
  "period_type": 1,
  "is_blocked": false
}

###
DELETE http://localhost:8091/api/notifications/37

###
GET http://localhost:8091/api/notifications

###
POST http://localhost:8091/api/agents/1/notifications/7?page=1&size=2&sort=priority

###
GET http://localhost:8091/api/agents/1/notifications/7/unread

###
PATCH http://localhost:8091/api/agents/1/notifications/7/71